name: untitled
description: A simple StageXL web app.
version: 0.0.1
#homepage: https://www.example.com
#author: hzzt <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
  intl: ^0.15.8

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0


